// https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-advanced/cambridge-international-as-and-a-levels/subjects/
export const ALEVEL_EXAMS = [
	'Accounting',
	'Arabic',
	'Art & Design',
	'Biblical Studies',
	'Biology',
	'Business',
	'Chemistry',
	'Chinese - Language & Literature',
	'Chinese',
	'Classical Studies',
	'Computer Science',
	'Design & Technology',
	'Design & Textiles',
	'Digital Media & Design',
	'Drama',
	'Economics',
	'English - Literature',
	'English Language',
	'French',
	'French Language & Literature',
	'Geography',
	'German',
	'German Language & Literature',
	'Global Perspectives & Research',
	'Hindi',
	'Hinduism',
	'History',
	'Information Technology',
	'Islamic Studies',
	'Law',
	'Marine Science',
	'Mathematics',
	'Mathematics - Further',
	'Media Studies',
	'Music',
	'Physical Education',
	'Physics',
	'Portuguese',
	'Psychology',
	'Sociology',
	'Spanish - Language & Literature',
	'Spanish',
	'Tamil - Language',
	'Thinking Skills',
	'Travel & Tourism',
	'Urdu'
] as const;
