export const AP_EXAMS = [
	'2-D Art and Design',
	'3-D Art and Design',
	'Art History',
	'Biology',
	'Calculus AB',
	'Calculus BC',
	'Chemistry',
	'Chinese Language and Culture',
	'Comparative Government and Politics',
	'Computer Science A',
	'Computer Science Principles',
	'Drawing',
	'English Language and Composition',
	'English Literature and Composition',
	'Environmental Science',
	'European History',
	'French Language and Culture',
	'German Language and Culture',
	'Human Geography',
	'Italian Language and Culture',
	'Japanese Language and Culture',
	'Latin',
	'Macroeconomics',
	'Microeconomics',
	'Music Theory',
	'Physics 1: Algebra-Based',
	'Physics 2: Algebra-Based',
	'Physics C: Electricity and Magnetism',
	'Physics C: Mechanics',
	'Precalculus',
	'Psychology',
	'Research',
	'Seminar',
	'Spanish Language and Culture',
	'Spanish Literature and Culture',
	'Statistics',
	'United States Government and Politics',
	'United States History',
	'World History: Modern'
] as const;
