export const IB_EXAMS = [
	'Biology HL',
	'Biology SL',
	'Business Management HL',
	'Business Management SL',
	'Chemistry HL',
	'Chemistry SL',
	'Classical Languages HL',
	'Classical Languages SL',
	'Computer Science HL',
	'Computer Science SL',
	'Dance HL',
	'Dance SL',
	'Design Technology HL',
	'Design Technology SL',
	'Economics HL',
	'Economics SL',
	'Environmental Systems and Societies SL',
	'Film HL',
	'Film SL',
	'Geography HL',
	'Geography SL',
	'Global Politics HL',
	'Global Politics SL',
	'History HL',
	'History SL',
	'Information Technology in a Global Society HL',
	'Information Technology in a Global Society SL',
	'Language A: Language & Literature HL',
	'Language A: Language & Literature SL',
	'Language A: Literature HL',
	'Language A: Literature SL',
	'Language B HL',
	'Language B SL',
	'Language ab Initio SL',
	'Literature and Performance SL',
	'Mathematics: Analysis and Approaches HL',
	'Mathematics: Analysis and Approaches SL',
	'Mathematics: Applications and Interpretation HL',
	'Mathematics: Applications and Interpretation SL',
	'Music HL',
	'Music SL',
	'Philosophy HL',
	'Philosophy SL',
	'Physics HL',
	'Physics SL',
	'Psychology HL',
	'Psychology SL',
	'Social and Cultural Anthropology HL',
	'Social and Cultural Anthropology SL',
	'Sports, Exercise, and Health Science HL',
	'Sports, Exercise, and Health Science SL',
	'Theatre HL',
	'Theatre SL',
	'Visual Arts HL',
	'Visual Arts SL',
	'World Religions SL'
];
