# Generated by Django 4.2.4 on 2023-08-06 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_application_cf_exclude'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOEFL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('reading', models.PositiveSmallIntegerField()),
                ('listening', models.PositiveSmallIntegerField()),
                ('speaking', models.PositiveSmallIntegerField()),
                ('writing', models.PositiveSmallIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'TOEFL',
            },
        ),
        migrations.CreateModel(
            name='SAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('ebrw', models.PositiveSmallIntegerField()),
                ('math', models.PositiveSmallIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'SAT',
            },
        ),
        migrations.CreateModel(
            name='IELTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('listening', models.DecimalField(decimal_places=1, max_digits=2)),
                ('reading', models.DecimalField(decimal_places=1, max_digits=2)),
                ('writing', models.DecimalField(decimal_places=1, max_digits=2)),
                ('speaking', models.DecimalField(decimal_places=1, max_digits=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'IELTS',
            },
        ),
        migrations.CreateModel(
            name='GRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('verbal', models.PositiveSmallIntegerField()),
                ('quant', models.PositiveSmallIntegerField()),
                ('writing', models.DecimalField(decimal_places=1, max_digits=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'GRE',
            },
        ),
        migrations.CreateModel(
            name='DET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('overall', models.PositiveSmallIntegerField()),
                ('literacy', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comprehension', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('conversation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('production', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'DET',
            },
        ),
        migrations.CreateModel(
            name='AP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=100)),
                ('score', models.PositiveSmallIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'AP',
            },
        ),
        migrations.CreateModel(
            name='ACT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('english', models.PositiveSmallIntegerField()),
                ('math', models.PositiveSmallIntegerField()),
                ('reading', models.PositiveSmallIntegerField()),
                ('science', models.PositiveSmallIntegerField()),
                ('writing', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'ACT',
            },
        ),
    ]
