# Generated by Django 4.2.4 on 2023-08-07 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_toefl_sat_ielts_gre_det_ap_act'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentlog',
            options={'get_latest_by': ['pinned', 'updated'], 'ordering': ['-pinned', '-updated']},
        ),
    ]
