# Generated by Django 4.2.4 on 2023-08-18 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0002_studentlog_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlog',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_logs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
