# Generated by Django 4.2.4 on 2023-08-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentlog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('verbal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quant', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reasoning', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('writing', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'GMAT scores',
            },
        ),
    ]
