# Generated by Django 4.2.4 on 2023-08-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_classrank_rank_alter_classrank_top_x'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'verbose_name_plural': 'ACT scores'},
        ),
        migrations.AlterModelOptions(
            name='ap',
            options={'verbose_name_plural': 'AP scores'},
        ),
        migrations.AlterModelOptions(
            name='det',
            options={'verbose_name_plural': 'DET scores'},
        ),
        migrations.AlterModelOptions(
            name='gpa',
            options={'verbose_name_plural': 'GPAs'},
        ),
        migrations.AlterModelOptions(
            name='gre',
            options={'verbose_name_plural': 'GRE scores'},
        ),
        migrations.AlterModelOptions(
            name='ielts',
            options={'verbose_name_plural': 'IELTS scores'},
        ),
        migrations.AlterModelOptions(
            name='sat',
            options={'verbose_name_plural': 'SAT scores'},
        ),
        migrations.AlterModelOptions(
            name='toefl',
            options={'verbose_name_plural': 'TOEFL scores'},
        ),
        migrations.AlterField(
            model_name='ielts',
            name='listening',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='ielts',
            name='reading',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='ielts',
            name='speaking',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='ielts',
            name='writing',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='toefl',
            name='listening',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toefl',
            name='reading',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toefl',
            name='speaking',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toefl',
            name='writing',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='ielts',
            constraint=models.CheckConstraint(check=models.Q(('listening__isnull', False), ('reading__isnull', False), ('writing__isnull', False), ('speaking__isnull', False), _connector='OR'), name='ielts_requires_at_least_one_subscore'),
        ),
        migrations.AddConstraint(
            model_name='toefl',
            constraint=models.CheckConstraint(check=models.Q(('reading__isnull', False), ('listening__isnull', False), ('speaking__isnull', False), ('writing__isnull', False), _connector='OR'), name='toefl_requires_at_least_one_subscore'),
        ),
    ]
