# Generated by Django 4.2.4 on 2023-08-18 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_application_submitting_act_and_more'),
        ('student', '0004_gmat'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmat',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gmat',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmat',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='core.student'),
            preserve_default=False,
        ),
    ]
