# Generated by Django 4.2.4 on 2023-08-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_act_options_alter_ap_options_alter_det_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ielts',
            name='ielts_requires_at_least_one_subscore',
        ),
        migrations.RemoveConstraint(
            model_name='toefl',
            name='toefl_requires_at_least_one_subscore',
        ),
        migrations.AlterField(
            model_name='act',
            name='english',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='math',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='reading',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='science',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ap',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='det',
            name='overall',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gre',
            name='quant',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gre',
            name='verbal',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gre',
            name='writing',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='sat',
            name='ebrw',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sat',
            name='math',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
