# Generated by Django 4.2.4 on 2023-08-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_gmat_comments_gmat_date_gmat_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='starts_as',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='starting_progression',
            field=models.CharField(choices=[('High School G9 - Fall', 'High School G9 - Fall'), ('High School G9 - Spring', 'High School G9 - Spring'), ('High School G10 - Fall', 'High School G10 - Fall'), ('High School G10 - Spring', 'High School G10 - Spring'), ('High School G11 - Fall', 'High School G11 - Fall'), ('High School G11 - Spring', 'High School G11 - Spring'), ('High School G12 - Fall', 'High School G12 - Fall'), ('High School G12 - Spring', 'High School G12 - Spring'), ('College Year 1 - Fall', 'College Year 1 - Fall'), ('College Year 1 - Spring', 'College Year 1 - Spring'), ('College Year 2 - Fall', 'College Year 2 - Fall'), ('College Year 2 - Spring', 'College Year 2 - Spring'), ('College Year 3 - Fall', 'College Year 3 - Fall'), ('College Year 3 - Spring', 'College Year 3 - Spring'), ('College Year 4 - Fall', 'College Year 4 - Fall'), ('College Year 4 - Spring', 'College Year 4 - Spring')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classrank',
            name='progression',
            field=models.CharField(choices=[('High School G9 - Fall', 'High School G9 - Fall'), ('High School G9 - Spring', 'High School G9 - Spring'), ('High School G10 - Fall', 'High School G10 - Fall'), ('High School G10 - Spring', 'High School G10 - Spring'), ('High School G11 - Fall', 'High School G11 - Fall'), ('High School G11 - Spring', 'High School G11 - Spring'), ('High School G12 - Fall', 'High School G12 - Fall'), ('High School G12 - Spring', 'High School G12 - Spring'), ('College Year 1 - Fall', 'College Year 1 - Fall'), ('College Year 1 - Spring', 'College Year 1 - Spring'), ('College Year 2 - Fall', 'College Year 2 - Fall'), ('College Year 2 - Spring', 'College Year 2 - Spring'), ('College Year 3 - Fall', 'College Year 3 - Fall'), ('College Year 3 - Spring', 'College Year 3 - Spring'), ('College Year 4 - Fall', 'College Year 4 - Fall'), ('College Year 4 - Spring', 'College Year 4 - Spring')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gpa',
            name='progression',
            field=models.CharField(choices=[('High School G9 - Fall', 'High School G9 - Fall'), ('High School G9 - Spring', 'High School G9 - Spring'), ('High School G10 - Fall', 'High School G10 - Fall'), ('High School G10 - Spring', 'High School G10 - Spring'), ('High School G11 - Fall', 'High School G11 - Fall'), ('High School G11 - Spring', 'High School G11 - Spring'), ('High School G12 - Fall', 'High School G12 - Fall'), ('High School G12 - Spring', 'High School G12 - Spring'), ('College Year 1 - Fall', 'College Year 1 - Fall'), ('College Year 1 - Spring', 'College Year 1 - Spring'), ('College Year 2 - Fall', 'College Year 2 - Fall'), ('College Year 2 - Spring', 'College Year 2 - Spring'), ('College Year 3 - Fall', 'College Year 3 - Fall'), ('College Year 3 - Spring', 'College Year 3 - Spring'), ('College Year 4 - Fall', 'College Year 4 - Fall'), ('College Year 4 - Spring', 'College Year 4 - Spring')], max_length=50),
        ),
    ]
