# Generated by Django 4.2.4 on 2023-08-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_enrollment_starts_as_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='program_type',
            field=models.CharField(choices=[('Pre-College', 'Pre-College'), ('UG Freshman', 'UG Freshman'), ('UG Transfer', 'UG Transfer'), ('Master', 'Master'), ('PhD', 'PhD'), ('Other', 'Other')], max_length=100),
        ),
    ]
