# Generated by Django 4.2.4 on 2023-08-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_application_submitting_act_and_more'),
        ('student', '0008_alter_enrollment_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='submitting_act', to='core.application'),
        ),
        migrations.AddField(
            model_name='ap',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='submitting_ap', to='core.application'),
        ),
        migrations.AddField(
            model_name='det',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='submitting_det', to='core.application'),
        ),
        migrations.AddField(
            model_name='gmat',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='submitting_gmat', to='core.application'),
        ),
        migrations.AddField(
            model_name='gre',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='submitting_gre', to='core.application'),
        ),
        migrations.AddField(
            model_name='ielts',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='submitting_ielts', to='core.application'),
        ),
        migrations.AddField(
            model_name='sat',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='submitting_sat', to='core.application'),
        ),
        migrations.AddField(
            model_name='toefl',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='submitting_toefl', to='core.application'),
        ),
    ]
