# Generated by Django 4.2.4 on 2023-08-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_application_submitting_act_and_more'),
        ('student', '0009_act_used_for_ap_used_for_det_used_for_gmat_used_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='act_submitted', to='core.application'),
        ),
        migrations.AlterField(
            model_name='ap',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='ap_submitted', to='core.application'),
        ),
        migrations.AlterField(
            model_name='det',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='det_submitted', to='core.application'),
        ),
        migrations.AlterField(
            model_name='gmat',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='gmat_submitted', to='core.application'),
        ),
        migrations.AlterField(
            model_name='gre',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='gre_submitted', to='core.application'),
        ),
        migrations.AlterField(
            model_name='ielts',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='ielts_submitted', to='core.application'),
        ),
        migrations.AlterField(
            model_name='sat',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='sat_submitted', to='core.application'),
        ),
        migrations.AlterField(
            model_name='toefl',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='toefl_submitted', to='core.application'),
        ),
    ]
