# Generated by Django 4.2.4 on 2023-09-03 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_delete_studentlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='end_term',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='start_term',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='start_year',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 9, 3)),
            preserve_default=False,
        ),
    ]
