# Generated by Django 4.2.4 on 2023-09-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_applicationlog_status'),
        ('student', '0012_remove_enrollment_end_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='curriculum',
            field=models.CharField(blank=True, choices=[('AP', 'AP'), ('IBDP', 'IBDP'), ('A-Level', 'A-Level'), ('Gaokao', 'Gaokao')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gmat',
            name='quant',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gmat',
            name='reasoning',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gmat',
            name='verbal',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toefl',
            name='listening',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toefl',
            name='reading',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toefl',
            name='speaking',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toefl',
            name='writing',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LSAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='core.student')),
                ('used_for', models.ManyToManyField(blank=True, related_name='lsat_submitted', to='core.application')),
            ],
            options={
                'verbose_name_plural': 'LSAT scores',
            },
        ),
        migrations.CreateModel(
            name='IB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=100)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='core.student')),
                ('used_for', models.ManyToManyField(blank=True, related_name='ib_submitted', to='core.application')),
            ],
            options={
                'verbose_name_plural': 'IB scores',
            },
        ),
        migrations.CreateModel(
            name='Alevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=100)),
                ('percentage', models.SmallIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='core.student')),
                ('used_for', models.ManyToManyField(blank=True, related_name='alevel_submitted', to='core.application')),
            ],
            options={
                'verbose_name_plural': 'A-level scores',
            },
        ),
    ]
