# Generated by Django 4.2.4 on 2023-09-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_applicationlog_status'),
        ('student', '0013_alter_enrollment_curriculum_alter_gmat_quant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IB',
            new_name='IBPredicted',
        ),
        migrations.AlterModelOptions(
            name='ibpredicted',
            options={'verbose_name_plural': 'IB predicted scores'},
        ),
    ]
