# Generated by Django 4.2.4 on 2023-09-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_applicationlog_status'),
        ('student', '0015_ibfinal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alevel',
            options={'verbose_name_plural': 'A-level grades'},
        ),
        migrations.AlterModelOptions(
            name='ibpredicted',
            options={'verbose_name_plural': 'IB predicted grades'},
        ),
        migrations.AlterField(
            model_name='ibpredicted',
            name='used_for',
            field=models.ManyToManyField(blank=True, related_name='ib_predicted_submitted', to='core.application'),
        ),
        migrations.DeleteModel(
            name='IBFinal',
        ),
    ]
