# Generated by Django 4.2.4 on 2023-09-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_applicationlog_status'),
        ('student', '0016_alter_alevel_options_alter_ibpredicted_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ibpredicted',
            old_name='score',
            new_name='grade',
        ),
        migrations.CreateModel(
            name='IBFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='core.student')),
                ('used_for', models.ManyToManyField(blank=True, related_name='ib_final_submitted', to='core.application')),
            ],
            options={
                'verbose_name_plural': 'IB final grades',
            },
        ),
    ]
