# Generated by Django 4.2.4 on 2023-09-15 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_applicationlog_status'),
        ('student', '0018_alevelpredicted_delete_alevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlevelFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=100)),
                ('percentage', models.SmallIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='core.student')),
                ('used_for', models.ManyToManyField(blank=True, related_name='alevel_final_submitted', to='core.application')),
            ],
            options={
                'verbose_name_plural': 'A-level final grades',
            },
        ),
    ]
