# Generated by Django 4.2.4 on 2023-09-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alevelfinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='ending_progression',
            field=models.CharField(blank=True, choices=[('High School G9', 'High School G9'), ('High School G10', 'High School G10'), ('High School G11', 'High School G11'), ('High School G12', 'High School G12'), ('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Year 5', 'Year 5'), ('Master Year 1', 'Master Year 1'), ('Master Year 2', 'Master Year 2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='classrank',
            name='progression',
            field=models.CharField(choices=[('High School G9', 'High School G9'), ('High School G10', 'High School G10'), ('High School G11', 'High School G11'), ('High School G12', 'High School G12'), ('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Year 5', 'Year 5'), ('Master Year 1', 'Master Year 1'), ('Master Year 2', 'Master Year 2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='starting_progression',
            field=models.CharField(choices=[('High School G9', 'High School G9'), ('High School G10', 'High School G10'), ('High School G11', 'High School G11'), ('High School G12', 'High School G12'), ('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Year 5', 'Year 5'), ('Master Year 1', 'Master Year 1'), ('Master Year 2', 'Master Year 2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gpa',
            name='progression',
            field=models.CharField(choices=[('High School G9', 'High School G9'), ('High School G10', 'High School G10'), ('High School G11', 'High School G11'), ('High School G12', 'High School G12'), ('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Year 5', 'Year 5'), ('Master Year 1', 'Master Year 1'), ('Master Year 2', 'Master Year 2')], max_length=50),
        ),
    ]
