# Generated by Django 4.2.4 on 2023-09-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_enrollment_ending_progression_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrank',
            name='term',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Spring-Summer', 'Spring-Summer'), ('Winter', 'Winter'), ('Academic Year', 'Academic Year')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gpa',
            name='term',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Spring-Summer', 'Spring-Summer'), ('Winter', 'Winter'), ('Academic Year', 'Academic Year')], max_length=50),
        ),
    ]
