# Generated by Django 4.2.4 on 2023-08-31 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_alter_userlog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlog',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
