# Generated by Django 4.2.4 on 2023-09-01 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_applicationlog_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('target', '0007_remove_subtarget_deadline_subtarget_deadline_date_and_more'),
        ('writing', '0005_alter_userlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essay_tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(blank=True, max_length=1000)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(max_length=10000)),
                ('target_year', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essays', to='core.student')),
                ('contributors', models.ManyToManyField(blank=True, related_name='contributed_essays', to=settings.AUTH_USER_MODEL)),
                ('submitted_to', models.ManyToManyField(blank=True, related_name='essays', to='target.program')),
                ('tags', models.ManyToManyField(blank=True, related_name='essays', to='writing.essaytag')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_essays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='essaytag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner'), name='unique_tag_name_owner'),
        ),
    ]
