# Generated by Django 4.2.4 on 2023-09-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0006_essaytag_essay_essaytag_unique_tag_name_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlog',
            options={'get_latest_by': ['pinned', 'date', 'updated'], 'ordering': ['-pinned', '-date', '-updated']},
        ),
        migrations.RemoveIndex(
            model_name='userlog',
            name='writing_use_pinned_2a4f32_idx',
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['-pinned', '-date', '-updated'], name='writing_use_pinned_92b949_idx'),
        ),
    ]
