# Generated by Django 4.2.4 on 2023-09-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0007_alter_userlog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='public',
        ),
        migrations.AddField(
            model_name='userlog',
            name='task_due',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='task_status',
            field=models.CharField(choices=[('', ''), ('TODO', 'TODO'), ('Done', 'Done')], default='', max_length=20),
        ),
    ]
