# Generated by Django 4.2.4 on 2023-08-06 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('target', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('scholarship_currency', models.CharField(blank=True, max_length=50)),
                ('alt_admitted_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='alt_admissions', to='target.target')),
                ('cf_exclude', models.ManyToManyField(related_name='excluded_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('UG Freshman', 'UG Freshman'), ('UG Transfer', 'UG Transfer'), ('Graduate', 'Graduate')], max_length=100)),
                ('target_year', models.IntegerField()),
                ('date_signed', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Effective', 'Effective'), ('Fulfilled', 'Fulfilled'), ('Terminated', 'Terminated')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('name_in_chinese', models.BooleanField(default=True)),
                ('last_name_romanized', models.CharField(blank=True, max_length=50)),
                ('first_name_romanized', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=50)),
                ('citizenship', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('comments', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('文案', '文案'), ('顾问', '顾问'), ('战略顾问', '战略顾问'), ('服务顾问', '服务顾问')], max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cf_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.contract')),
            ],
        ),
        migrations.CreateModel(
            name='MajorChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('rank', models.PositiveIntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_choices', to='core.application')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.student'),
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Ready to Submit', 'Ready to Submit'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Admitted', 'Admitted'), ('Deferred', 'Deferred'), ('On Waitlist', 'On Waitlist'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled'), ('Withdrawn', 'Withdrawn'), ('Disqualified', 'Disqualified'), ('Application Closed', 'Application Closed'), ('Offer Declined', 'Offer Declined'), ('Enrolled', 'Enrolled')], max_length=50)),
                ('comments', models.TextField(blank=True, max_length=1000)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.application')),
            ],
            options={
                'ordering': ['-date', '-updated'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.student'),
        ),
        migrations.AddField(
            model_name='application',
            name='subtarget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='applications', to='target.subtarget'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(models.F('contract'), models.F('cf_person'), models.F('role'), name='unique_service_contract_cfperson_role'),
        ),
        migrations.AddConstraint(
            model_name='majorchoice',
            constraint=models.UniqueConstraint(models.F('application'), models.F('major'), name='unique_majorchoice_application_major'),
        ),
        migrations.AddConstraint(
            model_name='majorchoice',
            constraint=models.UniqueConstraint(models.F('application'), models.F('rank'), name='unique_majorchoice_application_rank'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(models.F('student'), models.F('type'), models.F('target_year'), name='unique_contract_student_type_targetyear'),
        ),
        migrations.AddIndex(
            model_name='applicationlog',
            index=models.Index(fields=['-date', '-updated'], name='core_applic_date_f675fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicationlog',
            constraint=models.UniqueConstraint(models.F('application'), models.F('status'), models.F('comments'), name='unique_applicationlog_application_status_comments'),
        ),
    ]
