# Generated by Django 4.2.4 on 2023-08-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_amount', models.PositiveIntegerField(default=0)),
                ('scholarship_currency', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Ready to Submit', 'Ready to Submit'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Deferred', 'Deferred'), ('On Waitlist', 'On Waitlist'), ('Admitted', 'Admitted'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled'), ('Withdrawn', 'Withdrawn'), ('Disqualified', 'Disqualified'), ('Application Closed', 'Application Closed'), ('Offer Declined', 'Offer Declined'), ('Enrolled', 'Enrolled')], max_length=50)),
                ('comments', models.TextField(blank=True, max_length=1000)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-updated'],
                'get_latest_by': ['date', 'updated'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('UG Freshman', 'UG Freshman'), ('UG Transfer', 'UG Transfer'), ('Graduate', 'Graduate')], max_length=100)),
                ('target_year', models.IntegerField()),
                ('date_signed', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Effective', 'Effective'), ('Fulfilled', 'Fulfilled'), ('Terminated', 'Terminated')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MajorChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('rank', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('文案', '文案'), ('顾问', '顾问'), ('服务顾问', '服务顾问'), ('战略顾问', '战略顾问')], max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('name_in_chinese', models.BooleanField(default=True)),
                ('last_name_romanized', models.CharField(blank=True, max_length=50)),
                ('first_name_romanized', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=50)),
                ('citizenship', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('comments', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
