# Generated by Django 4.2.4 on 2023-08-14 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('target', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cf_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.contract'),
        ),
        migrations.AddField(
            model_name='majorchoice',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_choices', to='core.application'),
        ),
        migrations.AddField(
            model_name='contract',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.student'),
        ),
        migrations.AddField(
            model_name='applicationlog',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.application'),
        ),
        migrations.AddField(
            model_name='application',
            name='alt_admitted_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='alt_admissions', to='target.target'),
        ),
        migrations.AddField(
            model_name='application',
            name='cf_exclude',
            field=models.ManyToManyField(blank=True, related_name='excluded_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.student'),
        ),
        migrations.AddField(
            model_name='application',
            name='subtarget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='applications', to='target.subtarget'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(models.F('contract'), models.F('cf_person'), models.F('role'), name='unique_service_contract_cfperson_role'),
        ),
        migrations.AddConstraint(
            model_name='majorchoice',
            constraint=models.UniqueConstraint(models.F('application'), models.F('major'), name='unique_majorchoice_application_major'),
        ),
        migrations.AddConstraint(
            model_name='majorchoice',
            constraint=models.UniqueConstraint(models.F('application'), models.F('rank'), name='unique_majorchoice_application_rank'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(models.F('student'), models.F('type'), models.F('target_year'), name='unique_contract_student_type_targetyear'),
        ),
        migrations.AddIndex(
            model_name='applicationlog',
            index=models.Index(fields=['-date', '-updated'], name='core_applic_date_f675fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicationlog',
            constraint=models.UniqueConstraint(models.F('application'), models.F('status'), models.F('comments'), name='unique_applicationlog_application_status_comments'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(models.F('student'), models.F('subtarget'), name='unique_application_student_subtarget'),
        ),
    ]
