# Generated by Django 4.2.4 on 2023-08-06 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cf_exclude',
            field=models.ManyToManyField(blank=True, related_name='excluded_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
