# Generated by Django 4.2.4 on 2023-08-15 15:47

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('last_name'), django.db.models.functions.text.Lower('first_name'), django.db.models.functions.text.Lower('last_name_romanized'), django.db.models.functions.text.Lower('first_name_romanized'), models.F('date_of_birth'), name='unique_student_names_dateofbirth'),
        ),
    ]
