# Generated by Django 4.2.4 on 2023-08-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_application_cf_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='scholarship_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
