# Generated by Django 4.2.4 on 2023-08-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_applicationlog_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationlog',
            options={'get_latest_by': ['date', 'updated'], 'ordering': ['-date', '-updated']},
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(models.F('student'), models.F('subtarget'), name='unique_application_student_subtarget'),
        ),
    ]
