# Generated by Django 4.2.4 on 2023-08-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_student_unique_student_names_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submitting_act',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='submitting_det',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='submitting_gre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='submitting_ielts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='submitting_sat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='submitting_toefl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='majorchoice',
            name='major_category',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
