# Generated by Django 4.2.4 on 2023-08-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_name_in_chinese_student_last_name_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'CF products',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='cf_products',
            field=models.ManyToManyField(blank=True, related_name='students', to='core.cfproduct'),
        ),
    ]
