# Generated by Django 4.2.4 on 2023-08-18 15:22

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cfproduct_student_cf_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='student_progression_at_signing',
            field=models.CharField(blank=True, choices=[('High School G9 - Fall', 'High School G9 - Fall'), ('High School G9 - Spring', 'High School G9 - Spring'), ('High School G10 - Fall', 'High School G10 - Fall'), ('High School G10 - Spring', 'High School G10 - Spring'), ('High School G11 - Fall', 'High School G11 - Fall'), ('High School G11 - Spring', 'High School G11 - Spring'), ('High School G12 - Fall', 'High School G12 - Fall'), ('High School G12 - Spring', 'High School G12 - Spring'), ('College Year 1 - Fall', 'College Year 1 - Fall'), ('College Year 1 - Spring', 'College Year 1 - Spring'), ('College Year 2 - Fall', 'College Year 2 - Fall'), ('College Year 2 - Spring', 'College Year 2 - Spring'), ('College Year 3 - Fall', 'College Year 3 - Fall'), ('College Year 3 - Spring', 'College Year 3 - Spring'), ('College Year 4 - Fall', 'College Year 4 - Fall'), ('College Year 4 - Spring', 'College Year 4 - Spring')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='cfproduct',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_cfproduct_name'),
        ),
    ]
