# Generated by Django 4.2.4 on 2023-08-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contract_student_progression_at_signing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submitting_gmat',
            field=models.BooleanField(default=False),
        ),
    ]
