# Generated by Django 4.2.4 on 2023-08-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_application_submitting_gmat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='submitting_act',
        ),
        migrations.RemoveField(
            model_name='application',
            name='submitting_det',
        ),
        migrations.RemoveField(
            model_name='application',
            name='submitting_gmat',
        ),
        migrations.RemoveField(
            model_name='application',
            name='submitting_gre',
        ),
        migrations.RemoveField(
            model_name='application',
            name='submitting_ielts',
        ),
        migrations.RemoveField(
            model_name='application',
            name='submitting_sat',
        ),
        migrations.RemoveField(
            model_name='application',
            name='submitting_toefl',
        ),
    ]
