# Generated by Django 4.2.4 on 2023-09-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_contract_student_progression_at_signing'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationlog',
            name='unique_applicationlog_application_status_comments',
        ),
        migrations.AddConstraint(
            model_name='applicationlog',
            constraint=models.UniqueConstraint(models.F('application'), models.F('status'), condition=models.Q(('status__in', ['Under Review', 'Deferred', 'On Waitlist']), _negated=True), name='unique_applicationlog_application_status'),
        ),
        migrations.AddConstraint(
            model_name='applicationlog',
            constraint=models.UniqueConstraint(models.F('application'), models.F('status'), models.F('comments'), condition=models.Q(('status__in', ['Under Review', 'Deferred', 'On Waitlist'])), name='unique_applicationlog_application_status_comments'),
        ),
    ]
